### ISSUE TITLE
View feeds by source/categories

### ISSUE THREAD

**Issue by nshki** [nshki/reader#1]
From this thread: https://twitter.com/nshki_/status/1003832162322350080

For users that have a large number of feeds, it would be useful to be able to view links by source, rather than having a crazy number of links presented on the get-go.

Another request was to be able to create your own categories to organize feed sources into them.

**Comment by unwaivering** [comment]
Lol I subscribe to a lot of constantly updating feeds so I might still have a massive amount of links, but I'd like to keep them limited to various feeds instead of all in one huge timeline. I don't particularly want my recipes being right next to links from HN etc. I guess I'm old-fashioned in that RSS should be more like it used to be, and not like Twitter. Also creating categories/folders would be great!
